//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PUMPTRUCK
    {
        public string S_PT_ID { get; set; }
        public string S_SPBH { get; set; }
        public string S_PT_NAME { get; set; }
        public string S_PZ { get; set; }
        public string S_PT_FLOW { get; set; }
        public string S_PT_LIFT { get; set; }
        public string N_PT_CLASS { get; set; }
        public string S_ADD { get; set; }
        public string S_PT_AREA { get; set; }
        public string S_SYSCOMMANDOID { get; set; }
        public string S_PT_CONTACTS { get; set; }
        public string S_PT_CONTACTPHONE { get; set; }
        public string S_BZ { get; set; }
        public string S_QX { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
